# Generated by Django 4.1.7 on 2023-04-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_surname_alter_supplier_company'),
        ('brand', '0002_alter_brand_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
