# Generated by Django 4.1.7 on 2023-04-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_surname_alter_supplier_company'),
        ('brand', '0003_brand_supplier_alter_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='supplier.supplier'),
        ),
    ]
