# Generated by Django 4.1.7 on 2023-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
